name: Generate Datas
permissions:
  contents: write
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk/svg-only@v2
        id: snake-gif
        with:
          github_user_name: vibx27
          outputs: |
            github-snake.svg

      - uses: dailydotdev/action-devcard@2.0.4
        id: dailydev
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
